<div>
    <input type="button" id="add_button" value="Add">
</div>

<div id="table-container"></div>
<script type="text/javascript">
    document.observe('dom:loaded', function() {
        var event = new eventManager({
            'container_id': 'table-container',
            'data': <?php print_r (json_encode($this->getPrimaryId()))?>
        })
    })
</script>
<style>
    /* Style for the table */
table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
}

th,
td {
    border: 1px solid #ddd;
    padding: 10px; /* Increased padding for better spacing */
    text-align: left;
}

/* Style for the table header */
th {
    background-color: #f2f2f2;
    color: #333; /* Darkened text color for better contrast */
}

/* Style for input fields */
input[type="text"] {
    width: 100%;
    padding: 8px;
    box-sizing: border-box;
    border: 1px solid #ccc; /* Added border for input fields */
    border-radius: 5px; /* Rounded corners for input fields */
    transition: border-color 0.3s ease; /* Smooth transition for focus effect */
}

input[type="text"]:focus {
    border-color: #4CAF50;
    outline: none;
}

#addButton {
    color: white;
    margin-top: 10px;
    padding: 8px 15px; 
    border: none;
    cursor: pointer;
    border-radius: 3px;
}

#deleteRowButton{
    margin-top: 10px;
    margin-right: 10px;
    color: white;
    padding: 8px 15px; 
    border: none;
    cursor: pointer;
    border-radius: 3px;
}
#deleteTableButton {
    color: white;
    padding: 8px 15px; 
    margin: 2px;
    border: none;
    cursor: pointer;
    border-radius: 3px;
}


/* Style for Add Button outside the table */
#add_button {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    border-radius: 5px;
    font-size: 16px;
    transition: opacity 0.3s ease; /* Smooth transition for hover effect */
}

#add_button:hover {
    opacity: 0.8;
}
select {
    width: 100%;
    padding: 8px;
    box-sizing: border-box;
    border: 1px solid #ccc; /* Added border for select dropdown */
    border-radius: 5px; /* Rounded corners */
    appearance: none; /* Remove default arrow */
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20' fill='%231e88e5'%3E%3Cpath d='M10 12l-8-8H2l8 8 8-8h-1.1L10 12.9 3.1 5H2.1L10 13.1 17.9 5H16.9l-8 8z'/%3E%3C/svg%3E");
    background-repeat: no-repeat;
    background-position-x: calc(100% - 10px); /* Position the arrow icon */
    background-position-y: center;
    cursor: pointer;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    transition: border-color 0.3s ease; /* Smooth transition for focus effect */
}

select:focus {
    border-color: #4CAF50;
    outline: none;
}
</style>