<!-- Seller dropdown and Load Repoort button -->
<select name="seller_id" id="seller" class="no-changes">
    <option value="default">-----select-----</option>
    <?php
    $data = Mage::getModel('Ccc_Productseller/productseller')->getCollection();
    foreach ($data->getData() as $data) {

    ?>
        <option value="<?php echo $data['seller_name'] ?>"><?php echo $data['seller_name'] ?></option>

    <?php } ?>
</select>
<button class="load_report">Load Report</button>
<br>
<br>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>